/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensisiswa;

/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDataSiswa = new javax.swing.JMenuItem();
        menuDataKelas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuInputAbsensi = new javax.swing.JMenuItem();
        menuRekapAbsensi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_admin.png"))); // NOI18N

        jMenu1.setText("Dara Master");

        menuDataSiswa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDataSiswa.setText("Data Siswa");
        menuDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataSiswaActionPerformed(evt);
            }
        });
        jMenu1.add(menuDataSiswa);

        menuDataKelas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDataKelas.setText("Data Kelas");
        menuDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataKelasActionPerformed(evt);
            }
        });
        jMenu1.add(menuDataKelas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Absensi");

        menuInputAbsensi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        menuInputAbsensi.setText("Input Absensi");
        menuInputAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInputAbsensiActionPerformed(evt);
            }
        });
        jMenu2.add(menuInputAbsensi);

        menuRekapAbsensi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        menuRekapAbsensi.setText("Rekap Absensi");
        menuRekapAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRekapAbsensiActionPerformed(evt);
            }
        });
        jMenu2.add(menuRekapAbsensi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataSiswaActionPerformed
        new FormSiswa().setVisible(true);
    }//GEN-LAST:event_menuDataSiswaActionPerformed

    private void menuInputAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInputAbsensiActionPerformed
        new FormAbsensi().setVisible(true);
    }//GEN-LAST:event_menuInputAbsensiActionPerformed

    private void menuDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataKelasActionPerformed
        new FormKelas().setVisible(true);
    }//GEN-LAST:event_menuDataKelasActionPerformed

    private void menuRekapAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRekapAbsensiActionPerformed
        new FormRekapAbsensi().setVisible(true);
    }//GEN-LAST:event_menuRekapAbsensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuDataKelas;
    private javax.swing.JMenuItem menuDataSiswa;
    private javax.swing.JMenuItem menuInputAbsensi;
    private javax.swing.JMenuItem menuRekapAbsensi;
    // End of variables declaration//GEN-END:variables
}
